fix flaky ci failures caused by this action
Here's an example failure: https://github.com/PalisadeResearch/template/actions/runs/21082659633/job/60639666374

    Run if [ -n "$(git status --porcelain)" ]; then
    Error: Figures are out of date. Please rebuild figures and commit the changes.
    1️⃣ Git status shows:
    ?? result
    2️⃣ Git diff shows:
    Error: Process completed with exit code 1.

The culprit here is that untracked `result` file. That file is the
output of a `nix build` command -- the one in this CI action. `nix
build` creates a `result` symlink to its output by default. CI actions
that consume this one and do not expect that file to be there, like the
one linked above, can fail if that file is present. Worse, that failure
is flaky because it depends on whether there is a nix cache hit or not.

The fix is simple: just tell nix not to create that symlink, via
`--no-link`. We aren't using the symlink anyway.